version: "3"
services:

   mysql:
      image: mysql
      container_name: mysql
      ports:
        - 3306:3306
      volumes:
        - ./dbdata:/var/lib/mysql/
      restart: always
      secrets:
        - dbpass
      environment:
         MYSQL_DATABASE: "test"
         MYSQL_ROOT_PASSWORD: /run/secrets/dbpass

   php:
      build: .
      container_name: php
      volumes:
        - ./code:/code

   web:
      image: nginx:latest
      container_name: web
      ports:
         - "80:80"
      volumes:
        - ./code:/code
        - ./default.conf:/etc/nginx/conf.d/default.conf
      links:
        - "php"
        - "mysql"

secrets:
    dbpass:
       file: "./dbpass.txt"






